spring.application.name=yavigestion
spring.application.version=1.0.0
server.port=${SERVER_PORT:8080}
server.servlet.context-path=/yavirac


# Postgres config
spring.datasource.url=${POSTGRES_URL:jdbc:postgresql://51.222.157.250:5478/yavirac}
spring.datasource.username=${POSTGRES_USER:yavirac}
spring.datasource.password=${POSTGRES_PASS:mVYQrZeuvqWd5JKHDD53QY8Yhp37yjVzuu3ZQ5JktHJLTwgbNeGneXS2XPLKzsDz}
spring.jpa.hibernate.ddl-auto=update

app.jwt.secret=K5+/pD6Cz07j3X1G9KqvH8XbJQePwE5w1W3DHe6p7B+jkTfKImBz5pS7p3zljm4n8N9PZxq1mP3rHsBz9b5T1w==
app.jwt.expiration-ms=90000000

app.front.url=http://localhost:4200
